version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Pokedex-app-react
permissions:
  - object: /home/ec2-user/Pokedex-app-react
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user



